<?php
/**
 * Settings page.
 *
 * @package AlwaysAnalytics
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$always_analytics_options = wp_parse_args(
	get_option( 'always_analytics_options', array() ),
	array(
		'disable_tracking'    => false,
		'tracking_mode'       => 'cookieless',
		'cookieless_window'   => 'daily',
		'excluded_roles'      => array( 'administrator' ),
		'excluded_ips'        => '',
		'trusted_proxy_mode'  => 'none',
		'trusted_proxies'     => '',
		'anonymize_ip'        => true,
		'retention_days'      => 90,
		'delete_on_uninstall' => false,
		'cache_ttl'           => 300,
		'external_favicons'   => false,
		'export_format'       => 'csv',
		'consent_message'     => __( 'This site uses audience measurement cookies. Do you agree?', 'always-analytics' ),
		'consent_accept'      => __( 'Accept', 'always-analytics' ),
		'consent_decline'     => __( 'Decline', 'always-analytics' ),
		'consent_bg_color'    => '#1a1a2e',
		'consent_text_color'  => '#ffffff',
		'consent_btn_color'   => '#6c63ff',
	)
);
$always_analytics_mode    = 'cookie' === $always_analytics_options['tracking_mode'] ? 'cookie' : 'cookieless';
?>
<div class="wrap always-analytics-wrap always-analytics-settings-page"
	data-tracking-mode="<?php echo esc_attr( $always_analytics_mode ); ?>"
	data-cookie-title="<?php echo esc_attr__( 'With cookie', 'always-analytics' ); ?>"
	data-cookie-summary="<?php echo esc_attr__( 'Persistent first-party identification after explicit acceptance.', 'always-analytics' ); ?>"
	data-cookie-banner="<?php echo esc_attr__( 'Consent banner enabled', 'always-analytics' ); ?>"
	data-cookieless-title="<?php echo esc_attr__( 'Cookieless', 'always-analytics' ); ?>"
	data-cookieless-summary="<?php echo esc_attr__( 'No persistent visitor cookie and no plugin consent banner.', 'always-analytics' ); ?>"
	data-cookieless-banner="<?php echo esc_attr__( 'No visitor banner', 'always-analytics' ); ?>"
>
	<h1 class="screen-reader-text"><?php echo esc_html__( 'Always Analytics settings', 'always-analytics' ); ?></h1>

	<div class="always-analytics-header">
		<div class="always-analytics-header-title"><img src="<?php echo esc_url( ALWAYS_ANALYTICS_PLUGIN_URL . 'always-analytics.svg' ); ?>" alt="" class="always-analytics-logo-img"><?php echo esc_html__( 'Always Analytics settings', 'always-analytics' ); ?></div>
		<div class="always-analytics-header-actions"><a href="<?php echo esc_url( admin_url( 'admin.php?page=always-analytics' ) ); ?>" class="button"><?php echo esc_html__( 'Back to dashboard', 'always-analytics' ); ?></a><span class="always-analytics-version-badge">v<?php echo esc_html( ALWAYS_ANALYTICS_VERSION ); ?></span></div>
	</div>

	<?php settings_errors( 'always_analytics_options' ); ?>

	<form id="always-analytics-settings-form" method="post" action="options.php">
		<?php settings_fields( 'always_analytics_settings' ); ?>

		<section class="aa-settings-hero">
			<div>
				<span class="aa-settings-eyebrow"><?php echo esc_html__( 'Collection profile', 'always-analytics' ); ?></span>
				<h2><?php echo esc_html__( 'Choose how visitors are identified', 'always-analytics' ); ?></h2>
				<p><?php echo esc_html__( 'Select one profile. The page automatically shows only the settings that apply to that mode.', 'always-analytics' ); ?></p>
			</div>
			<label class="aa-switch aa-switch-danger"><input type="checkbox" name="always_analytics_options[disable_tracking]" value="1" <?php checked( ! empty( $always_analytics_options['disable_tracking'] ) ); ?>><span></span><strong><?php echo esc_html__( 'Pause collection', 'always-analytics' ); ?></strong></label>
		</section>

		<div class="aa-mode-grid" role="radiogroup" aria-label="<?php echo esc_attr__( 'Tracking mode', 'always-analytics' ); ?>">
			<label class="aa-mode-card" data-mode-card="cookieless" for="always-analytics-mode-cookieless">
				<input class="aa-mode-radio" id="always-analytics-mode-cookieless" type="radio" name="always_analytics_options[tracking_mode]" value="cookieless" <?php checked( $always_analytics_mode, 'cookieless' ); ?>>
				<span class="aa-mode-icon dashicons dashicons-shield"></span>
				<strong><?php echo esc_html__( 'Cookieless', 'always-analytics' ); ?></strong>
				<em><?php echo esc_html__( 'Recommended', 'always-analytics' ); ?></em>
				<p><?php echo esc_html__( 'No persistent visitor cookie and no consent banner generated by the plugin. IP truncation is enforced.', 'always-analytics' ); ?></p>
				<ul><li><?php echo esc_html__( 'Local, first-party measurement', 'always-analytics' ); ?></li><li><?php echo esc_html__( 'Daily or browser-session uniqueness', 'always-analytics' ); ?></li><li><?php echo esc_html__( 'Simplest configuration', 'always-analytics' ); ?></li></ul>
				<span class="aa-mode-action"><span class="dashicons dashicons-arrow-right-alt2"></span><?php echo esc_html__( 'Select this mode', 'always-analytics' ); ?></span>
			</label>
			<label class="aa-mode-card" data-mode-card="cookie" for="always-analytics-mode-cookie">
				<input class="aa-mode-radio" id="always-analytics-mode-cookie" type="radio" name="always_analytics_options[tracking_mode]" value="cookie" <?php checked( $always_analytics_mode, 'cookie' ); ?>>
				<span class="aa-mode-icon dashicons dashicons-admin-users"></span>
				<strong><?php echo esc_html__( 'With cookie', 'always-analytics' ); ?></strong>
				<em><?php echo esc_html__( 'Advanced', 'always-analytics' ); ?></em>
				<p><?php echo esc_html__( 'Creates a persistent first-party identifier only after the visitor accepts the analytics banner.', 'always-analytics' ); ?></p>
				<ul><li><?php echo esc_html__( 'More stable returning-visitor measurement', 'always-analytics' ); ?></li><li><?php echo esc_html__( 'Consent banner enabled automatically', 'always-analytics' ); ?></li><li><?php echo esc_html__( 'Developer testing supported', 'always-analytics' ); ?></li></ul>
				<span class="aa-mode-action"><span class="dashicons dashicons-arrow-right-alt2"></span><?php echo esc_html__( 'Select this mode', 'always-analytics' ); ?></span>
			</label>
		</div>

		<div class="aa-settings-layout">
			<main class="aa-settings-main">
				<section class="aa-settings-card" data-mode-panel="cookieless">
					<header><span class="dashicons dashicons-chart-area"></span><div><h2><?php echo esc_html__( 'Cookieless measurement', 'always-analytics' ); ?></h2><p><?php echo esc_html__( 'Only settings relevant to cookieless collection are shown.', 'always-analytics' ); ?></p></div></header>
					<div class="aa-setting-row"><div><strong><?php echo esc_html__( 'Unique visitor window', 'always-analytics' ); ?></strong><p><?php echo esc_html__( 'Choose how long an anonymous identifier remains comparable.', 'always-analytics' ); ?></p></div><select name="always_analytics_options[cookieless_window]"><option value="daily" <?php selected( $always_analytics_options['cookieless_window'], 'daily' ); ?>><?php echo esc_html__( 'One UTC day', 'always-analytics' ); ?></option><option value="session" <?php selected( $always_analytics_options['cookieless_window'], 'session' ); ?>><?php echo esc_html__( 'Browser session only', 'always-analytics' ); ?></option></select></div>
					<div class="aa-setting-row aa-setting-locked"><div><strong><?php echo esc_html__( 'IP truncation', 'always-analytics' ); ?></strong><p><?php echo esc_html__( 'Always enabled in cookieless mode.', 'always-analytics' ); ?></p></div><span class="aa-status-pill aa-status-on"><?php echo esc_html__( 'Enforced', 'always-analytics' ); ?></span><input type="hidden" name="always_analytics_options[anonymize_ip]" value="1"></div>
					<div class="aa-setting-row aa-setting-locked"><div><strong><?php echo esc_html__( 'Visitor banner', 'always-analytics' ); ?></strong><p><?php echo esc_html__( 'No banner is displayed by Always Analytics in cookieless mode.', 'always-analytics' ); ?></p></div><span class="aa-status-pill"><?php echo esc_html__( 'Disabled', 'always-analytics' ); ?></span></div>
				</section>

				<section class="aa-settings-card" data-mode-panel="cookie">
					<header><span class="dashicons dashicons-privacy"></span><div><h2><?php echo esc_html__( 'Cookie consent banner', 'always-analytics' ); ?></h2><p><?php echo esc_html__( 'This banner is enabled automatically when cookie mode is selected.', 'always-analytics' ); ?></p></div></header>
					<div class="aa-settings-warning"><span class="dashicons dashicons-warning"></span><p><?php echo esc_html__( 'Cookie mode stores a persistent first-party identifier after acceptance. Verify that your site information and consent workflow match your actual use before production deployment.', 'always-analytics' ); ?></p></div>
					<div class="aa-field-stack"><label><strong><?php echo esc_html__( 'Banner message', 'always-analytics' ); ?></strong><input type="text" class="large-text" name="always_analytics_options[consent_message]" value="<?php echo esc_attr( $always_analytics_options['consent_message'] ); ?>"></label><div class="aa-field-columns"><label><strong><?php echo esc_html__( 'Accept button', 'always-analytics' ); ?></strong><input type="text" name="always_analytics_options[consent_accept]" value="<?php echo esc_attr( $always_analytics_options['consent_accept'] ); ?>"></label><label><strong><?php echo esc_html__( 'Decline button', 'always-analytics' ); ?></strong><input type="text" name="always_analytics_options[consent_decline]" value="<?php echo esc_attr( $always_analytics_options['consent_decline'] ); ?>"></label></div></div>
					<div class="aa-color-grid"><label><span><?php echo esc_html__( 'Background', 'always-analytics' ); ?></span><input type="color" name="always_analytics_options[consent_bg_color]" value="<?php echo esc_attr( $always_analytics_options['consent_bg_color'] ); ?>"></label><label><span><?php echo esc_html__( 'Text', 'always-analytics' ); ?></span><input type="color" name="always_analytics_options[consent_text_color]" value="<?php echo esc_attr( $always_analytics_options['consent_text_color'] ); ?>"></label><label><span><?php echo esc_html__( 'Primary button', 'always-analytics' ); ?></span><input type="color" name="always_analytics_options[consent_btn_color]" value="<?php echo esc_attr( $always_analytics_options['consent_btn_color'] ); ?>"></label></div>
					<div class="aa-setting-row"><div><strong><?php echo esc_html__( 'Truncate IP addresses', 'always-analytics' ); ?></strong><p><?php echo esc_html__( 'Recommended even in cookie mode.', 'always-analytics' ); ?></p></div><label class="aa-switch"><input type="checkbox" name="always_analytics_options[anonymize_ip]" value="1" <?php checked( ! empty( $always_analytics_options['anonymize_ip'] ) ); ?>><span></span></label></div>
				</section>

				<section class="aa-settings-card">
					<header><span class="dashicons dashicons-database"></span><div><h2><?php echo esc_html__( 'Data and accuracy', 'always-analytics' ); ?></h2><p><?php echo esc_html__( 'Control retention, exclusions and proxy handling.', 'always-analytics' ); ?></p></div></header>
					<div class="aa-setting-row"><div><strong><?php echo esc_html__( 'Raw data retention', 'always-analytics' ); ?></strong><p><?php echo esc_html__( 'Older detailed records are anonymized by the scheduled cleanup.', 'always-analytics' ); ?></p></div><select name="always_analytics_options[retention_days]">
					<?php
					foreach ( array( 30, 90, 180, 365, 395 ) as $always_analytics_retention_choice ) :
						?>
						<option value="<?php echo esc_attr( $always_analytics_retention_choice ); ?>" <?php selected( (int) $always_analytics_options['retention_days'], $always_analytics_retention_choice ); ?>><?php echo esc_html( sprintf( /* translators: %d: retention period in days. */ _n( '%d day', '%d days', $always_analytics_retention_choice, 'always-analytics' ), $always_analytics_retention_choice ) ); ?></option><?php endforeach; ?></select></div>
					<div class="aa-field-stack"><label><strong><?php echo esc_html__( 'Excluded roles', 'always-analytics' ); ?></strong><span class="aa-help"><?php echo esc_html__( 'Logged-in users with these roles are not counted.', 'always-analytics' ); ?></span><div class="aa-check-grid">
					<?php
					foreach ( wp_roles()->get_names() as $always_analytics_role_key => $always_analytics_role_name ) :
						?>
						<label><input type="checkbox" name="always_analytics_options[excluded_roles][]" value="<?php echo esc_attr( $always_analytics_role_key ); ?>" <?php checked( in_array( $always_analytics_role_key, (array) $always_analytics_options['excluded_roles'], true ) ); ?>><?php echo esc_html( translate_user_role( $always_analytics_role_name ) ); ?></label><?php endforeach; ?></div></label></div>
					<div class="aa-field-columns"><label><strong><?php echo esc_html__( 'Excluded IP addresses', 'always-analytics' ); ?></strong><span class="aa-help"><?php echo esc_html__( 'One IP address or CIDR range per line.', 'always-analytics' ); ?></span><textarea name="always_analytics_options[excluded_ips]" rows="5" class="large-text code"><?php echo esc_textarea( $always_analytics_options['excluded_ips'] ); ?></textarea></label><label><strong><?php echo esc_html__( 'Trusted proxy addresses', 'always-analytics' ); ?></strong><span class="aa-help"><?php echo esc_html__( 'Used only when custom proxy mode is enabled.', 'always-analytics' ); ?></span><textarea name="always_analytics_options[trusted_proxies]" rows="5" class="large-text code"><?php echo esc_textarea( $always_analytics_options['trusted_proxies'] ); ?></textarea></label></div>
					<div class="aa-setting-row"><div><strong><?php echo esc_html__( 'Proxy headers', 'always-analytics' ); ?></strong><p><?php echo esc_html__( 'Trust forwarded client addresses only from proxies you explicitly list.', 'always-analytics' ); ?></p></div><select name="always_analytics_options[trusted_proxy_mode]"><option value="none" <?php selected( $always_analytics_options['trusted_proxy_mode'], 'none' ); ?>><?php echo esc_html__( 'Do not trust proxy headers', 'always-analytics' ); ?></option><option value="custom" <?php selected( $always_analytics_options['trusted_proxy_mode'], 'custom' ); ?>><?php echo esc_html__( 'Trust listed proxies only', 'always-analytics' ); ?></option></select></div>
				</section>

				<section class="aa-settings-card">
					<header><span class="dashicons dashicons-performance"></span><div><h2><?php echo esc_html__( 'Interface and performance', 'always-analytics' ); ?></h2><p><?php echo esc_html__( 'Dashboard cache, favicons and exports.', 'always-analytics' ); ?></p></div></header>
					<div class="aa-setting-row"><div><strong><?php echo esc_html__( 'Dashboard cache', 'always-analytics' ); ?></strong><p><?php echo esc_html__( 'Between 60 and 3600 seconds.', 'always-analytics' ); ?></p></div><input type="number" min="60" max="3600" name="always_analytics_options[cache_ttl]" value="<?php echo esc_attr( (int) $always_analytics_options['cache_ttl'] ); ?>"></div>
					<div class="aa-setting-row"><div><strong><?php echo esc_html__( 'Google S2 favicons', 'always-analytics' ); ?></strong><p><?php echo esc_html__( "Loads external site icons in the WordPress administration. Google's service receives the administrator's IP address and the requested domain.", 'always-analytics' ); ?></p></div><label class="aa-switch"><input type="checkbox" name="always_analytics_options[external_favicons]" value="1" <?php checked( ! empty( $always_analytics_options['external_favicons'] ) ); ?>><span></span></label></div>
					<div class="aa-setting-row"><div><strong><?php echo esc_html__( 'Default export format', 'always-analytics' ); ?></strong></div><select name="always_analytics_options[export_format]"><option value="csv" <?php selected( $always_analytics_options['export_format'], 'csv' ); ?>>CSV</option><option value="json" <?php selected( $always_analytics_options['export_format'], 'json' ); ?>>JSON</option></select></div>
					<div class="aa-setting-row"><div><strong><?php echo esc_html__( 'Delete data on uninstall', 'always-analytics' ); ?></strong><p><?php echo esc_html__( 'Permanently removes plugin tables and options when the plugin is deleted.', 'always-analytics' ); ?></p></div><label class="aa-switch aa-switch-danger"><input type="checkbox" name="always_analytics_options[delete_on_uninstall]" value="1" <?php checked( ! empty( $always_analytics_options['delete_on_uninstall'] ) ); ?>><span></span></label></div>
				</section>
			</main>

			<aside class="aa-settings-sidebar">
				<div class="aa-summary-card"><span class="aa-settings-eyebrow"><?php echo esc_html__( 'Active profile', 'always-analytics' ); ?></span><h3 data-mode-summary-title></h3><p data-mode-summary-text></p><div class="aa-summary-list"><span><i class="dashicons dashicons-yes"></i><?php echo esc_html__( 'Self-hosted analytics data', 'always-analytics' ); ?></span><span data-summary-banner><i class="dashicons dashicons-yes"></i></span><span><i class="dashicons dashicons-yes"></i><?php echo esc_html__( 'No advertising tracking', 'always-analytics' ); ?></span></div></div>
				<div class="aa-summary-card aa-summary-muted"><h3><?php echo esc_html__( 'Developer note', 'always-analytics' ); ?></h3><p><?php echo esc_html__( 'Mode safeguards are also enforced during option sanitization. A crafted request cannot enable the cookie banner in cookieless mode or disable consent handling in cookie mode.', 'always-analytics' ); ?></p></div>
			</aside>
		</div>

		<div class="aa-settings-savebar"><div><strong><?php echo esc_html__( 'Ready to apply these settings?', 'always-analytics' ); ?></strong><span><?php echo esc_html__( 'The selected profile controls which visitor-side features are active.', 'always-analytics' ); ?></span></div><?php submit_button( __( 'Save settings', 'always-analytics' ), 'primary', 'submit', false ); ?></div>
	</form>
</div>
