<?php
/**
 * Export handler — generates CSV and JSON reports.
 *
 * @package Always_Analytics
 */

namespace Always_Analytics;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Export handler — generates CSV and JSON reports.
 */
class Always_Analytics_Export {

	/**
	 * Generate an export based on the given parameters.
	 *
	 * @param array  $params Filter parameters (from, to, post_type, device).
	 * @param string $format 'csv' or 'json'.
	 * @return string File content.
	 */
	public static function generate( $params, $format = 'csv' ) {
		global $wpdb;

		$where = array( '1=1' );
		$args  = array();

		if ( ! empty( $params['from'] ) ) {
			$where[] = 'hit_at >= %s';
			$args[]  = sanitize_text_field( $params['from'] ) . ' 00:00:00';
		}

		if ( ! empty( $params['to'] ) ) {
			$where[] = 'hit_at <= %s';
			$args[]  = sanitize_text_field( $params['to'] ) . ' 23:59:59';
		}

		if ( ! empty( $params['post_type'] ) ) {
			$where[] = 'post_type = %s';
			$args[]  = sanitize_key( $params['post_type'] );
		}

		if ( ! empty( $params['device'] ) ) {
			$where[] = 'device_type = %s';
			$args[]  = sanitize_text_field( $params['device'] );
		}

		$where_clause = implode( ' AND ', $where );

		$query = "SELECT
            hit_at, page_url, page_title, post_type,
            referrer_domain, utm_source, utm_medium, utm_campaign,
            device_type, browser, os,
            is_new_visitor, screen_width, screen_height
        FROM {$wpdb->prefix}always_analytics_hits
        WHERE {$where_clause}
        ORDER BY hit_at DESC
        LIMIT 50000";

		if ( ! empty( $args ) ) {
			// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.PreparedSQL.NotPrepared -- Export reads a plugin-owned table; the SQL is assembled only from fixed clauses and every variable value is represented by a placeholder.
			$results = $wpdb->get_results( $wpdb->prepare( $query, ...$args ), ARRAY_A );
		} else {
			// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.PreparedSQL.NotPrepared -- Export reads a plugin-owned table; without filters this query contains no variable values and therefore has no placeholders to prepare.
			$results = $wpdb->get_results( $query, ARRAY_A );
		}

		if ( empty( $results ) ) {
			$results = array();
		}

		/**
		 * Filter export data before generation.
		 *
		 * @param array  $results The result data.
		 * @param string $format  The format (csv/json).
		 */
		$results = apply_filters( 'always_analytics_export_data', $results, $format );

		if ( 'json' === $format ) {
			return self::to_json( $results );
		}

		return self::to_csv( $results );
	}

	/**
	 * Convert results to CSV string.
	 *
	 * @param array $results Rows to export.
	 * @return string
	 */
	private static function to_csv( $results ) {
		if ( empty( $results ) ) {
			return '';
		}

		ob_start();
		$output = fopen( 'php://output', 'w' );

		fputcsv( $output, array_keys( $results[0] ) );

		foreach ( $results as $row ) {
			fputcsv( $output, array_map( array( __CLASS__, 'guard_csv_formula' ), $row ) );
		}

		fclose( $output );
		return ob_get_clean();
	}

	/**
	 * Prevents CSV formula injection when the export is opened in spreadsheet
	 * software: values starting with =, +, -, @, tab, or CR are prefixed with
	 * a leading apostrophe so they are treated as plain text, not formulas.
	 *
	 * @param mixed $value Cell value.
	 * @return mixed
	 */
	private static function guard_csv_formula( $value ) {
		if ( ! is_string( $value ) || '' === $value ) {
			return $value;
		}

		if ( 1 === preg_match( '/^[=+\-@\t\r]/', $value ) ) {
			return "'" . $value;
		}

		return $value;
	}

	/**
	 * Convert results to JSON string.
	 *
	 * @param array $results Rows to export.
	 * @return string
	 */
	private static function to_json( $results ) {
		return wp_json_encode( $results, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE );
	}

	/**
	 * Send export as a file download.
	 *
	 * @param array  $params Filter parameters.
	 * @param string $format 'csv' or 'json'.
	 */
	public static function download( $params, $format = 'csv' ) {
		$content   = self::generate( $params, $format );
		$extension = ( 'json' === $format ) ? 'json' : 'csv';
		$mime_type = ( 'json' === $format ) ? 'application/json' : 'text/csv';
		$filename  = 'always-analytics-export-' . gmdate( 'Y-m-d-His' ) . '.' . $extension;

		header( 'Content-Type: ' . $mime_type . '; charset=utf-8' );
		header( 'Content-Disposition: attachment; filename="' . $filename . '"' );
		header( 'Pragma: no-cache' );
		header( 'Expires: 0' );

		if ( 'csv' === $format ) {
			echo "\xEF\xBB\xBF";
		}

		echo $content; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Raw CSV or JSON download payload generated by this class; HTML escaping would corrupt the exported file.
		exit;
	}
}
